# Generated by Django 4.2.29 on 2026-03-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_note_is_pinned_alter_note_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
