# Generated by Django 4.2.29 on 2026-03-21 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0002_synclog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spreadsheet_id', models.CharField(max_length=500)),
                ('service_account_json', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
