# Generated by Django 4.2.29 on 2026-03-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_sheetconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
