# Generated by Django 4.2.29 on 2026-03-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobapplication_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='interview_prep',
            field=models.TextField(blank=True),
        ),
    ]
