# Generated by Django 4.2.29 on 2026-03-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobapplication_interview_prep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='company',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
